apiVersion: v1
kind: InstallConfig
baseDomain: abays.testing
compute:
 - name: worker
   replicas: 1
controlPlane:
   name: master
   platform: {}
   replicas: 1
metadata:
   name: cluster
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
   none: {}
   apiVIP: 192.168.111.5
   ingressVIP: 192.168.111.4
   dnsVIP: 192.168.111.3
   hosts: []

pullSecret: 'PULL_SECRET'
sshKey: |
   SSH_PUB_KEY
